title: TeamUSA2025
description: A team project to apply the Fiscal Sustainability Model from excel sheets into a web-based platform.
google_analytics:
show_downloads: false
theme: jekyll-theme-slate
github:
  is_project_page: true
  repository_url: https://github.com/teamusa2025/teamusa2025-project
gems:
  - jekyll-mentions
